batch_size: 64

dataset: 'mnist_data'
model_train: 'mni_cnn'


gpu_num: "2, 3"
attack_method: 'CW'

MNIST_checkpoint_path: 'model/mnist_model'
HARD_MNIST_checkpoint_path: 'model/hard_mnist_model'

attack_eps: 0.2